name = "huggg-challenge-api"
main = "src/index.ts"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[env.development]
[env.development.vars]
ENVIRONMENT = "development"

[env.production]
[env.production.vars]
ENVIRONMENT = "production"