name = "huggg-challenge-api"
main = "src/index.ts"
compatibility_date = "2023-05-18"
compatibility_flags = ["nodejs_compat"]

[env.development]
[env.development.vars]
ENVIRONMENT = "development"

[env.staging]
workers_dev = true
[env.staging.vars]
ENVIRONMENT = "staging"

[env.production]
workers_dev = false
[env.production.vars]
ENVIRONMENT = "production"