export type Product = {
	id: string;
	created_at: string;
	updated_at: string;
	brand_id: string;
	description: string;
	campaign: string | null;
	label: string;
	internal_name: string;
	integration: string;
	price: string;
	over_18_offer: number;
	redemption_instructions: string;
	image: string;
	subtitle: string;
	weight: number;
	recipient_description: string;
	tag_group_id: string;
	tag_id: string;
	open_graph_image: string;
	active: number;
	on_app: number;
	on_imessage: number;
	handling_fee: number;
	sale_price: number;
	huggg_tag: string | null;
	vat_voucher_type: string;
	vat: number | null;
	brand_name: string;
	brand_weight: number;
	image_url: string | null;
	claim_image: string;
	claim_image_url: string | null;
	imessage_image: string;
	imessage_image_url: string | null;
	open_graph_image_url: string;
	pivot?: {
		brand_id: string;
		price_id: string;
	};
};

export type Store = {
	id: string;
	brand_id: string;
	latitiude: string;
	longitude: string;
	website: string | null;
	name: string;
	description: string;
	visible: number;
	description_markdown: string;
	image: string;
	image_url: string;
	latitude: string;
};
